name = "worker-links"
main = "src/index.ts"

# optional
#logpush = true

# Change these!!
kv_namespaces = [
  
  # Replace below line with your namespace ID ('yarn createkv' output) 
  { binding = "LINKS", id = "4a36476e04df4040a7aa79cb2bfafd7d", preview_id = "373541152e4848c9909210beb1d9d8bf" }

  ]

compatibility_flags = []
compatibility_date = "2023-11-08"

# Remove or comment out the route line if using workers_dev (and set below to true)
workers_dev = true
#route = { pattern = "erisa.link/*", zone_name = "erisa.link" }

[vars]
ENABLE_INDEX_FORM = true
